version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true

  user-auth-service:
    build: 
      # context: //path to specify to the src of a service when running multiple services
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9602:9602
    environment:
      - JWTSECRET=idreamitiworkhardigrindtilliownit
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/USER-AUTH-Service

