version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    networks:
      - mynetwork
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - mynetwork
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true

  rabbitmq:
    image: rabbitmq:3.9-rc-management
    restart: always
    networks:
      - mynetwork
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
    env_file:
      - rabbitmq.conf

    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5

  product-service:
    build: 
      # context: //path to specify to the src of a service when running multiple services
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - mynetwork
    ports:
      - 9601:9601
    environment:
      - JWTSECRET=idreamitiworkhardigrindtilliownit
      - RABBITMQ_DEFAULT_USER=jayy22
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_HOST=rabbitmq
      - RABBITMQ_DEFAULT_PORT=5672

networks:
  mynetwork:
    driver: bridge