name: Create comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action-api:
    runs-on: ubuntu-latest
    steps:
      - name: "Create comment with API"
        run: |
          gh api -X POST \
            HTTP://api.github.com/repo/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER/comments} \
            -f body=" Comment from Github API Bot"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.organization.login }}
          REPOSITORY:  ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
